import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

/**
 * Vite plugin: generates `sw.js` at build time so DiliJump can be installed
 * and played offline.
 *
 * - Precaches the page, the hashed JS/CSS bundles and every file in public/
 *   (sprites, icons, manifest) except the ones listed in EXCLUDE.
 * - Precache requests bypass the HTTP cache (public/ files aren't hashed).
 * - The cache name contains a hash of all precached content, so each deploy
 *   gets a fresh cache and old ones are deleted on activation.
 * - Only same-origin GET requests are handled: the Supabase leaderboard
 *   (REST + realtime) always goes straight to the network.
 * - Navigations are network-first (a new deploy shows up immediately when
 *   online), falling back to the cached page when offline.
 */
const EXCLUDE = [/^404\.html$/, /^robots\.txt$/, /^og-image\./, /\.map$/, /^sw\.js$/];

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

export function serviceWorker({ navigationTimeoutMs = 3500 } = {}) {
  let publicDir;
  return {
    name: 'dilijump-service-worker',
    apply: 'build',
    configResolved(config) {
      publicDir = config.publicDir;
    },
    generateBundle(_options, bundle) {
      const hash = createHash('sha256');
      const files = [];

      for (const [fileName, chunk] of Object.entries(bundle)) {
        if (EXCLUDE.some((re) => re.test(fileName)) || fileName === 'index.html') continue;
        files.push(fileName);
        hash.update(fileName);
        hash.update(chunk.type === 'chunk' ? chunk.code : chunk.source);
      }
      for (const full of walk(publicDir)) {
        const rel = relative(publicDir, full).split(sep).join('/');
        if (EXCLUDE.some((re) => re.test(rel))) continue;
        files.push(rel);
        hash.update(rel);
        hash.update(readFileSync(full));
      }
      const html = bundle['index.html'];
      if (html) hash.update(html.source);
      files.sort();

      const version = hash.digest('hex').slice(0, 12);
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource({ version, files, navigationTimeoutMs }),
      });
    },
  };
}

function swSource({ version, files, navigationTimeoutMs }) {
  return `/* DiliJump service worker — generated by tools/vite/serviceWorker.js. Do not edit. */
const CACHE = 'dilijump-${version}';
const PRECACHE = ${JSON.stringify(['./', ...files], null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' })))).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('dilijump-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

function withTimeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error('timeout')), ms);
    promise.then((v) => { clearTimeout(t); resolve(v); }, (e) => { clearTimeout(t); reject(e); });
  });
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // Supabase etc.: network only

  if (req.mode === 'navigate') {
    event.respondWith(
      withTimeout(fetch(req), ${navigationTimeoutMs})
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put('./', copy));
          }
          return res;
        })
        .catch(() => caches.match('./')),
    );
    return;
  }

  event.respondWith(
    caches.match(req).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok && res.type === 'basic') {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;
}
