/**
 * Character skins for the Dressing Room. Skins are purely cosmetic: every
 * skin uses the same hitbox and physics, only the artwork changes.
 *
 * Artwork: `classic` is the original mascot (tools/process_sprites.py +
 * process_sheets.py); the others are generated by tools/process_skins.py,
 * which writes `skins.json` (hashed files, atlas grids, reference heights).
 */
import SKIN_ART from './skins.json';
import SPRITE_SHEETS from './spriteSheets.json';
import SPRITES_META from '../../public/assets/sprites/sprites.json';

export const DEFAULT_SKIN = 'classic';

/** Poses every skin provides as single images (the rest come from the sheets). */
export const SKIN_POSES = Object.freeze(['idle', 'shoot', 'hurt', 'cheer']);

// classic pose canvas (tools/process_sprites.py): 1 px = 1 unit, 320 units = draw height
const CLASSIC_CANVAS = SPRITES_META.canvas;

export const SKINS = Object.freeze([
  {
    id: 'classic',
    name: 'Classic',
    tagline: 'The original Dlicom hero with his cape.',
    price: 0,
    art: {
      poses: Object.fromEntries(
        SKIN_POSES.map((p) => [
          p,
          {
            file: `${p}.webp`,
            refHeight: CLASSIC_CANVAS[1],
            w: CLASSIC_CANVAS[0],
            h: CLASSIC_CANVAS[1],
          },
        ]),
      ),
      sheets: SPRITE_SHEETS,
      avatar: SKIN_ART.classic.avatar,
    },
  },
  {
    id: 'wings',
    name: 'Neon Wings',
    tagline: 'Glowing lime feathers. Pure style.',
    price: 100,
    art: SKIN_ART.wings,
  },
  {
    id: 'golden',
    name: 'Golden Seraph',
    tagline: 'Gold armor, galaxy wings and a dragon tail.',
    price: 200,
    art: SKIN_ART.golden,
  },
  {
    id: 'galaxy',
    name: 'Galaxy Nebula',
    tagline: 'A spiral galaxy suit, silver armor and flowing nebula ribbons.',
    price: 300,
    art: SKIN_ART.galaxy,
  },
]);

/**
 * Skins that were sold once and then removed, with the price paid. Anyone who
 * owned one gets the DLI back (once) the next time the game starts.
 */
export const RETIRED_SKINS = Object.freeze({ sunfire: 250 });

const BY_ID = new Map(SKINS.map((s) => [s.id, s]));

/** @returns {object|undefined} the skin definition */
export function getSkin(id) {
  return BY_ID.get(id);
}

const base = import.meta.env?.BASE_URL ?? './';
const spriteUrl = (file) => `${base}assets/sprites/${file}`;

/** AssetLoader keys for a skin's images. */
export const skinKey = {
  pose: (id, pose) => `skin.${id}.pose.${pose}`,
  sheet: (id, name) => `skin.${id}.sheet.${name}`,
  avatar: (id) => `skin.${id}.avatar`,
};

/** Public URL of one of a skin's pose images (for `<img>` in the UI). */
export function skinPoseUrl(id, pose) {
  const skin = getSkin(id) ?? getSkin(DEFAULT_SKIN);
  return spriteUrl(skin.art.poses[pose].file);
}

/**
 * Size of a pose image relative to the classic mascot's body height, so UI
 * images can be scaled to show every skin's body at the same size
 * (wings and tails make some canvases taller).
 */
export function skinPoseScale(id, pose) {
  const skin = getSkin(id) ?? getSkin(DEFAULT_SKIN);
  const m = skin.art.poses[pose];
  return m.h / m.refHeight;
}

export function skinAvatarUrl(id) {
  const skin = getSkin(id) ?? getSkin(DEFAULT_SKIN);
  return spriteUrl(skin.art.avatar);
}

/** Everything needed to play with a skin: poses, animation atlases, avatar. */
export function skinManifest(id) {
  const { art } = getSkin(id);
  return {
    images: {
      ...Object.fromEntries(
        Object.entries(art.poses).map(([p, m]) => [skinKey.pose(id, p), spriteUrl(m.file)]),
      ),
      ...Object.fromEntries(
        Object.entries(art.sheets).map(([n, m]) => [skinKey.sheet(id, n), spriteUrl(m.file)]),
      ),
      [skinKey.avatar(id)]: spriteUrl(art.avatar),
    },
  };
}

/** Dressing Room previews: every skin's idle pose (small, loaded at boot). */
export function skinPreviewManifest() {
  return {
    images: Object.fromEntries(
      SKINS.map((s) => [skinKey.pose(s.id, 'idle'), spriteUrl(s.art.poses.idle.file)]),
    ),
  };
}
